config/routes.rb
Naturesoft::Projects::Engine.routes.draw do
  namespace :backend, module: "backend", path: "backend/projects" do
    resources :projects do
      collection do
        put ':id/enable' => 'projects#enable', :as => 'enable'
        put ':id/disable' => 'projects#disable', :as => 'disable'
        delete 'delete'
      end
    end
    resources :categories do
      collection do
        put ':id/enable' => 'categories#enable', :as => 'enable'
        put ':id/disable' => 'categories#disable', :as => 'disable'
        delete 'delete'
        get "select2"
      end
    end
    resources :images do
      collection do
        put ':id/enable' => 'images#enable', :as => 'enable'
        put ':id/disable' => 'images#disable', :as => 'disable'
        delete 'delete'
      end
    end
  end
end

app/models/naturesoft/projects/image.rb
module Naturesoft::Projects
  class Image < ApplicationRecord
    belongs_to :project
    validates :image, presence: true
		validates :image, allow_blank: true, format: {
			with: %r{\.(gif|jpg|png)\Z}i,
			message: 'must be a URL for GIF, JPG or PNG image.'
		}
    mount_uploader :image, Naturesoft::Projects::ImageUploader
    
    def self.sort_by
      [
        ["Name","naturesoft_projects_images.name"],
        ["Created At","naturesoft_projects_images.created_at"]
      ]
    end
    def self.sort_orders
      [
        ["ASC","asc"],
        ["DESC","desc"]
      ]
    end
    
    #Filter, Sort
    def self.search(params)
      records = self.all
      
      #Search keyword filter
      if params[:keyword].present?
        params[:keyword].split(" ").each do |k|
          records = records.where("LOWER(CONCAT(naturesoft_projects_images.name,' ',naturesoft_projects_images.description)) LIKE ?", "%#{k.strip.downcase}%") if k.strip.present?
        end
      end
      
      # for sorting
      sort_by = params[:sort_by].present? ? params[:sort_by] : "naturesoft_projects_images.name"
      sort_orders = params[:sort_orders].present? ? params[:sort_orders] : "asc"
      records = records.order("#{sort_by} #{sort_orders}")
      
      return records
    end
    
    # enable/disable status
    def enable
			update_columns(status: "active")
		end
    
    def disable
			update_columns(status: "inactive")
		end
  end
end

app/controllers/naturesoft/projects/admin/images_controller.rb
module Naturesoft
  module Projects
    module Admin
      class ImagesController < Naturesoft::Admin::AdminController
        before_action :set_image, only: [:show, :edit, :update, :destroy, :enable, :disable]
        before_action :default_breadcrumb
        
        # add top breadcrumb
        def default_breadcrumb
          add_breadcrumb "Images Of Projects", naturesoft_projects.admin_images_path
        end
    
        # GET /images
        def index
          @images = Image.search(params).paginate(:page => params[:page], :per_page => 10)
        end
    
        # GET /images/1
        def show
          add_breadcrumb @image.name, naturesoft_projects.new_admin_image_path
          add_breadcrumb "Show"
        end
    
        # GET /images/new
        def new
          @image = Image.new
          add_breadcrumb "New Image", naturesoft_projects.new_admin_image_path
        end
    
        # GET /images/1/edit
        def edit
          add_breadcrumb @image.name, naturesoft_projects.new_admin_image_path
          add_breadcrumb "Edit"
        end
    
        # POST /images
        def create
          @image = Image.new(image_params)
    
          if @image.save
            redirect_to admin_images_path, notice: 'Image was successfully created.'
          else
            render :new
          end
        end
    
        # PATCH/PUT /images/1
        def update
          if @image.update(image_params)
            redirect_to admin_images_path, notice: 'Image was successfully updated.'
          else
            render :edit
          end
        end
    
        # DELETE /images/1
        def destroy
          @image.destroy
          render text: 'Image was successfully destroyed.'
        end
        
        # ENABLE /images/stutus
        def enable
          @image.enable
          render text: "Status was sucessfully enabled"
        end
        
        # DISABLE /images/stutus
        def disable
          @image.disable
          render text: "Status was sucessfully disabled"
        end
        
        # DELETE /images/delete?ids=1,2,3
        def delete
          @images = Image.where(id: params[:ids].split(","))
          @images.destroy_all
          render text: 'Image (s) was successfully destroyed.'
        end
    
        private
          # Use callbacks to share common setup or constraints between actions.
          def set_image
            @image = Image.find(params[:id])
          end
    
          # Only allow a trusted parameter "white list" through.
          def image_params
            params.fetch(:image, {}).permit(:name, :discription, :image, :project_id)
          end
      end
    end
  end
end

app/controllers/naturesoft/projects/backend/categories_controller.rb
module Naturesoft
  module Projects
    module Backend
      class CategoriesController < Naturesoft::Backend::BackendController
        before_action :set_category, only: [:show, :edit, :update, :destroy, :enable, :disable]
        before_action :default_breadcrumb
        
        # add top breadcrumb
        def default_breadcrumb
          add_breadcrumb "Categories Of Projects", naturesoft_projects.backend_categories_path
        end
    
        # GET /categories
        def index
          @categories = Category.search(params).paginate(:page => params[:page], :per_page => 10)
        end
    
        # GET /categories/1
        def show
          add_breadcrumb @category.name, naturesoft_projects.new_backend_category_path
          add_breadcrumb "Show"
        end
    
        # GET /categories/new
        def new
          @category = Category.new
          add_breadcrumb "New Category", naturesoft_projects.new_backend_category_path
        end
    
        # GET /categories/1/edit
        def edit
          add_breadcrumb @category.name, naturesoft_projects.new_backend_category_path
          add_breadcrumb "Edit"
        end
    
        # POST /categories
        def create
          @category = Category.new(category_params)
          @category.user = current_user
    
          if @category.save
            redirect_to backend_categories_path, notice: 'Category was successfully created.'
          else
            render :new
          end
        end
    
        # PATCH/PUT /categories/1
        def update
          if @category.update(category_params)
            redirect_to backend_categories_path, notice: 'Category was successfully updated.'
          else
            render :edit
          end
        end
    
        # DELETE /categories/1
        def destroy
          @category.destroy
          render text: 'Category was successfully destroyed.'
        end
        
        # ENABLE /categories/stutus
        def enable
          @category.enable
          render text: "Status was sucessfully enabled"
        end
        
        # DISABLE /categories/stutus
        def disable
          @category.disable
          render text: "Status was sucessfully disabled"
        end
        
        # DELETE /categories/delete?ids=1,2,3
        def delete
          @categories = Category.where(id: params[:ids].split(","))
          @categories.destroy_all
          render text: 'Categor(y/ies) was successfully destroyed.'
        end
        
        # GET /articles/select2
        def select2
          render json: Category.select2(params)
        end
    
        private
          # Use callbacks to share common setup or constraints between actions.
          def set_category
            @category = Category.find(params[:id])
          end
    
          # Only allow a trusted parameter "white list" through.
          def category_params
            params.fetch(:category, {}).permit(:name, :description)
          end
      end
    end
  end
end

app/controllers/naturesoft/projects/backend/images_controller.rb
module Naturesoft
  module Projects
    module Backend
      class ImagesController < Naturesoft::Backend::BackendController
        before_action :set_image, only: [:show, :edit, :update, :destroy, :enable, :disable]
        before_action :default_breadcrumb
        
        # add top breadcrumb
        def default_breadcrumb
          add_breadcrumb "Images Of Projects", naturesoft_projects.backend_images_path
        end
    
        # GET /images
        def index
          @images = Image.search(params).paginate(:page => params[:page], :per_page => 10)
        end
    
        # GET /images/1
        def show
          add_breadcrumb @image.name, naturesoft_projects.new_backend_image_path
          add_breadcrumb "Show"
        end
    
        # GET /images/new
        def new
          @image = Image.new
          add_breadcrumb "New Image", naturesoft_projects.new_backend_image_path
        end
    
        # GET /images/1/edit
        def edit
          add_breadcrumb @image.name, naturesoft_projects.new_backend_image_path
          add_breadcrumb "Edit"
        end
    
        # POST /images
        def create
          @image = Image.new(image_params)
    
          if @image.save
            redirect_to backend_images_path, notice: 'Image was successfully created.'
          else
            render :new
          end
        end
    
        # PATCH/PUT /images/1
        def update
          if @image.update(image_params)
            redirect_to backend_images_path, notice: 'Image was successfully updated.'
          else
            render :edit
          end
        end
    
        # DELETE /images/1
        def destroy
          @image.destroy
          render text: 'Image was successfully destroyed.'
        end
        
        # ENABLE /images/stutus
        def enable
          @image.enable
          render text: "Status was sucessfully enabled"
        end
        
        # DISABLE /images/stutus
        def disable
          @image.disable
          render text: "Status was sucessfully disabled"
        end
        
        # DELETE /images/delete?ids=1,2,3
        def delete
          @images = Image.where(id: params[:ids].split(","))
          @images.destroy_all
          render text: 'Image (s) was successfully destroyed.'
        end
    
        private
          # Use callbacks to share common setup or constraints between actions.
          def set_image
            @image = Image.find(params[:id])
          end
    
          # Only allow a trusted parameter "white list" through.
          def image_params
            params.fetch(:image, {}).permit(:name, :discription, :image, :project_id)
          end
      end
    end
  end
end

app/controllers/naturesoft/projects/backend/projects_controller.rb
module Naturesoft
  module Projects
    module Backend
      class ProjectsController < Naturesoft::Backend::BackendController
        before_action :set_project, only: [:show, :edit, :update, :destroy, :enable, :disable]
        before_action :default_breadcrumb
        
        # add top breadcrumb
        def default_breadcrumb
          add_breadcrumb "Projects", naturesoft_projects.backend_projects_path
        end
    
        # GET /projects
        def index
          @projects = Project.search(params).paginate(:page => params[:page], :per_page => Naturesoft::Option.get("projects", "items_per_page"))
        end
    
        # GET /projects/1
        def show
          add_breadcrumb @project.name, naturesoft_projects.new_backend_project_path
          add_breadcrumb "Show"
        end
    
        # GET /projects/new
        def new
          @project = Project.new
          add_breadcrumb "New Project", naturesoft_projects.new_backend_project_path
        end
    
        # GET /projects/1/edit
        def edit
          add_breadcrumb @project.name, naturesoft_projects.new_backend_project_path
          add_breadcrumb "Edit"
        end
    
        # POST /projects
        def create
          @project = Project.new(project_params)
          @project.categories.clear
          @project.user = current_user
          if params[:category_ids].present?
            params[:category_ids].each do |id|      
              @project.categories << Category.find(id)
            end
          end
    
          if @project.save
            redirect_to backend_projects_path, notice: 'Project was successfully created.'
          else
            render :new
          end
        end
    
        # PATCH/PUT /projects/1
        def update
          @project.categories.clear
          if params[:category_ids].present?
            params[:category_ids].each do |id|      
              @project.categories << Category.find(id)
            end
          end
          if @project.update(project_params)
            redirect_to backend_projects_path, notice: 'Project was successfully updated.'
          else
            render :edit
          end
        end
    
        # DELETE /projects/1
        def destroy
          @project.destroy
          render text: 'Project was successfully destroyed.'
        end
        
        # ENABLE /partners/stutus
        def enable
          @project.enable
          render text: "Status was sucessfully enabled"
        end
        
        # DISABLE /partners/stutus
        def disable
          @project.disable
          render text: "Status was sucessfully disabled"
        end
        
        # DELETE /projects/delete?ids=1,2,3
        def delete
          @projects = Project.where(id: params[:ids].split(","))
          @projects.destroy_all
          render text: 'Project(s) was successfully destroyed.'
        end
    
        private
          # Use callbacks to share common setup or constraints between actions.
          def set_project
            @project = Project.find(params[:id])
          end
    
          # Only allow a trusted parameter "white list" through.
          def project_params
            params.fetch(:project, {}).permit(:name,
              :description,
              :website,
              :investor,
              :start_date,
              :end_date,
              :category_id,
              images_attributes: [:id, :is_main, :image, :name, :_destroy]
            )
          end
      end
    end
  end
end

app/views/naturesoft/projects/backend/images/_form.html.erb
<% if image.errors.any? %>
  <div class="alert alert-warning alert-bordered">
    <button type="button" class="close" data-dismiss="alert"><span>×</span><span class="sr-only">Close</span></button>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this slide from being saved:</h2>
  
      <ul>
      <% image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

<div class="panel panel-flat">
  
  <div class="panel-heading"></div>
  
  <div class="panel-body">

    <%= form_for([naturesoft_projects, :backend, image], html: {class: "form-horizontal", id: "validate_checking", multipart: true}) do |f| %>
    
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label class="col-md-2 control-label" ><%= t(:image) %> </label>
            <div class="media no-margin-top col-md-10">
              <div class="media-left">
                <a href="#">
                  <% if image.image.present? %>
                    <img src="<%= image.image %>" style="width: 60px; height: 60px; border-radius: 2px;" alt="">
                  <% else %>
                    <img src="/backend/assets/images/placeholder.jpg" style="width: 60px; height: 60px; border-radius: 2px;" alt="">
                  <% end %>
                </a>
              </div>
        
              <div class="media-body">
                <input type="file" name="image[image]" class="file-styled">
                <span class="help-block">Accepted formats: gif, png, jpg.</span>
              </div>
            </div>
          </div>
        </div>
      </div>
        
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label class="col-md-2 control-label" ><%= t(:name) %> <span class='text-danger'>*</span></label>
            <div class="col-md-10">
              <%= f.text_field :name, class: "form-control required" %>
            </div>
          </div>
        </div>
      </div>
        
      <div class="form-group">
        <label class="col-md-2 control-label" ><%= t(:related_project) %> <span class='text-danger'>*</span></label>
        <div class="col-md-10">
          <%= f.collection_select(:project_id, Naturesoft::Projects::Project.all, :id, :name, {:prompt=> "Choose..."}, {class: "select2"}) %>
        </div>
      </div>
        
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <label class="col-md-2 control-label" ><%= t(:description) %> </label>
            <div class="col-md-10">
              <%= f.text_area :description, class: "form-control", style: "min-width:100%;max-width:100%" %>
            </div>
          </div>
        </div>
      </div>
    
      <div class="text-right">
        <%= button_tag "#{t(:save)}<i class=\"icon-check position-right\"></i>".html_safe, class: "btn btn-primary"%>
        <%= link_to "#{t(:cancel)}<i class=\"icon-cross3 position-right\"></i>".html_safe, naturesoft_projects.backend_images_path, class: "btn btn-danger"%>
      </div>
        
    <% end %>
  </div>
</div>

app/views/naturesoft/projects/backend/images/edit.html.erb
<% title "Edit Image: " + @image.name %>

<%= render 'form', image: @image %>

app/views/naturesoft/projects/backend/images/index.html.erb
<p id="notice"><%= notice %></p>

<% title "Project / Images" %>

<div class="page_actions">
    <%= link_to ("#{t(:new_image)}" + '<i class="icon-plus22 position-right"></i>').html_safe, naturesoft_projects.new_backend_image_path, class: 'btn btn-primary' %>
</div>
<br />

<form class="listing-form">
    
    <div class="panel panel-flat border-top-primary">
        <div class="panel-body filter-box">
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        <label><%= t(:sort_by) %></label>
                        <%= select_tag(:sort_by, options_for_select(Naturesoft::Projects::Image.sort_by, :selected => params[:sort_by]), class: "select2") %>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label><%= t(:sort_order) %></label>
                        <%= select_tag(:sort_orders, options_for_select(Naturesoft::Projects::Image.sort_orders, :selected => params[:sort_orders]), class: "select2") %>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group has-feedback">
                        <label><%= t(:search) %></label>
                        <input type="text" name="keyword" class="form-control" placeholder="Enter search..." value="<%= params[:key] %>">
                        <div class="form-control-feedback">
                            <i class="icon-search4 text-size-base"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="btn-group list_actions mb-10 hide">
        <button type="button" class="btn btn-xs btn-info dropdown-toggle" data-toggle="dropdown">
            Actions <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">											
            <li>
                <a href="" data-href="<%= naturesoft_projects.delete_backend_images_path %>" data-confirm="Are you sure!" data-method="DELETE">
                    <i class="icon-enter"></i> Delete
                </a>
            </li>            
        </ul>
    </div>
    <!-- Basic datatable -->
    <div class="panel panel-flat">        
        <div class="table-container">
            <table class="table table-striped">
                <thead>
                    <tr class="bg-teal-800">
                        <th width="1%" class="check_all_list">
                            <input type="checkbox" class="styled">
                        </th>
                        <th><%= t(:image) %></th>
                        <th><%= t(:name) %></th>
                        <th><%= t(:description) %></th>
                        <th><%= t(:created_at) %></th>
                        <th><%= t(:status) %></th>
                        <th class="text-right"><%= t(:actions) %></th>
                    </tr>
                </thead>
                <tbody>
                    <% @images.each do |image| %>
                        <tr>
                            <td width="1%">
                                <input type="checkbox" class="node styled"
                                    name="ids[]"
                                    value="<%= image.id %>"
                                />
                            </td>
                            <td>
                                <% if image.image.system.present? %>
                                    <%= link_to image_tag(image.image.system, size: "60x60", class: "img-rounded img-preview"), "" %>
                                <% else %>
                                    <img src="<%= url_for("/backend/assets/images/placeholder.jpg")%>" height="70" width="70" class="img-rounded img-preview">
                                <% end %>
                            </td>
                            <td>
                                <%= image.name %>
                            </td>
                            <td>
                                <%= image.description %>
                            </td>
                            <td><%= image.created_at.strftime("%d/%m/%Y") %></td>
                            <td><%= display_status(image.status) %></td>
                            <td class="text-right">
                                <div class="btn-group">
                                    <%= link_to '<i class="icon-pencil"></i>'.html_safe, naturesoft_projects.edit_backend_image_path(image), class: "btn bg-teal-400 btn-icon" %>
                                    <button type="button" class="btn bg-teal-400 dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><span class="caret"></span></button>
                                    <ul class="dropdown-menu dropdown-menu-right">
                                        <% if image.status == 'inactive' %>
                                            <li>
                                                <%= link_to "<i class=\"icon-unlocked2\"></i> Enable".html_safe, naturesoft_projects.enable_backend_images_path(image), method: :put %>
                                            </li>
                                        <% end %>
                                        <% if image.status == 'active' %>
                                            <li>
                                                <%= link_to "<i class=\"icon-lock2\"></i> Disable".html_safe, naturesoft_projects.disable_backend_images_path(image), method: :put %>
                                            </li>
                                        <% end %>
                                        <li class="divider"></li>
                                        <li>
                                            <%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe + t(:delete), naturesoft_projects.backend_image_path(image), method: :delete, data: { confirm: 'Are you sure?' } , class: "backend_delete_item" %>
                                        </li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        
        <div class="dataTables_wrapper no-footer">
            <div class="datatable-footer showed">
                <div class="dataTables_info" ><%= page_entries_info @images %></div>
                <div class="dataTables_paginate paging_simple_numbers">
                    <%= will_paginate @images, previous_label: '←', next_label: '→', renderer: BootstrapPagination::Rails %>
                </div>
            </div>
        </div>    
    </div>
    <!-- /basic datatable -->
</form>

app/views/naturesoft/projects/backend/images/new.html.erb
<% title "New Image" %>

<%= render 'form', image: @image %>

app/views/naturesoft/projects/backend/images/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>