config/routes.rb
Naturesoft::Projects::Engine.routes.draw do
  namespace :backend, module: "backend", path: "backend/projects" do
    resources :projects do
      collection do
        put ':id/enable' => 'projects#enable', :as => 'enable'
        put ':id/disable' => 'projects#disable', :as => 'disable'
        delete 'delete'
      end
    end
    resources :categories do
      collection do
        put ':id/enable' => 'categories#enable', :as => 'enable'
        put ':id/disable' => 'categories#disable', :as => 'disable'
        delete 'delete'
        get "select2"
      end
    end
    resources :images do
      collection do
        put ':id/enable' => 'images#enable', :as => 'enable'
        put ':id/disable' => 'images#disable', :as => 'disable'
        delete 'delete'
      end
    end
  end
end

app/models/naturesoft/projects/application_record.rb
module Naturesoft::Projects
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/naturesoft/projects/categories_project.rb
module Naturesoft::Projects
  class CategoriesProject < ApplicationRecord
    belongs_to :category
    belongs_to :project
  end
end

app/models/naturesoft/projects/project.rb
module Naturesoft::Projects
  class Project < ApplicationRecord
		include Naturesoft::CustomOrder
		
    belongs_to :user
    has_and_belongs_to_many :categories
    has_many :images, dependent: :destroy, :inverse_of => :project
    accepts_nested_attributes_for :images,
			:reject_if => lambda { |a| a[:image].blank? && a[:id].blank? },
			:allow_destroy => true
    
    def self.sort_by
      [
				["Custom order","naturesoft_projects_projects.custom_order"],
        ["Name","naturesoft_projects_projects.name"],
        ["Created At","naturesoft_projects_projects.created_at"]
      ]
    end
    def self.sort_orders
      [
        ["ASC","asc"],
        ["DESC","desc"]
      ]
    end
    
    #Filter, Sort
    def self.search(params)
      records = self.all
      
      #Search keyword filter
      if params[:keyword].present?
        params[:keyword].split(" ").each do |k|
          records = records.where("LOWER(CONCAT(naturesoft_projects_projects.name,' ',naturesoft_projects_projects.description)) LIKE ?", "%#{k.strip.downcase}%") if k.strip.present?
        end
      end
      
      # for sorting
      sort_by = params[:sort_by].present? ? params[:sort_by] : "naturesoft_projects_projects.name"
      sort_orders = params[:sort_orders].present? ? params[:sort_orders] : "asc"
      records = records.order("#{sort_by} #{sort_orders}")
      
      return records
    end
    
    # enable/disable status
    def enable
			update_columns(status: "active")
		end
    
    def disable
			update_columns(status: "inactive")
		end
    
    # get newest default image
    def main_image
			return Image.new if images.empty?
			
			img = images.where(is_main: true).last
			return img.nil? ? images.last : img
		end
  end
end

app/controllers/naturesoft/projects/admin/categories_controller.rb
module Naturesoft
  module Projects
    module Admin
      class CategoriesController < Naturesoft::Admin::AdminController
        before_action :set_category, only: [:show, :edit, :update, :destroy, :enable, :disable]
        before_action :default_breadcrumb
        
        # add top breadcrumb
        def default_breadcrumb
          add_breadcrumb "Categories Of Projects", naturesoft_projects.admin_categories_path
        end
    
        # GET /categories
        def index
          @categories = Category.search(params).paginate(:page => params[:page], :per_page => 10)
        end
    
        # GET /categories/1
        def show
          add_breadcrumb @category.name, naturesoft_projects.new_admin_category_path
          add_breadcrumb "Show"
        end
    
        # GET /categories/new
        def new
          @category = Category.new
          add_breadcrumb "New Category", naturesoft_projects.new_admin_category_path
        end
    
        # GET /categories/1/edit
        def edit
          add_breadcrumb @category.name, naturesoft_projects.new_admin_category_path
          add_breadcrumb "Edit"
        end
    
        # POST /categories
        def create
          @category = Category.new(category_params)
          @category.user = current_user
    
          if @category.save
            redirect_to admin_categories_path, notice: 'Category was successfully created.'
          else
            render :new
          end
        end
    
        # PATCH/PUT /categories/1
        def update
          if @category.update(category_params)
            redirect_to admin_categories_path, notice: 'Category was successfully updated.'
          else
            render :edit
          end
        end
    
        # DELETE /categories/1
        def destroy
          @category.destroy
          render text: 'Category was successfully destroyed.'
        end
        
        # ENABLE /categories/stutus
        def enable
          @category.enable
          render text: "Status was sucessfully enabled"
        end
        
        # DISABLE /categories/stutus
        def disable
          @category.disable
          render text: "Status was sucessfully disabled"
        end
        
        # DELETE /categories/delete?ids=1,2,3
        def delete
          @categories = Category.where(id: params[:ids].split(","))
          @categories.destroy_all
          render text: 'Categor(y/ies) was successfully destroyed.'
        end
        
        # GET /articles/select2
        def select2
          render json: Category.select2(params)
        end
    
        private
          # Use callbacks to share common setup or constraints between actions.
          def set_category
            @category = Category.find(params[:id])
          end
    
          # Only allow a trusted parameter "white list" through.
          def category_params
            params.fetch(:category, {}).permit(:name, :description)
          end
      end
    end
  end
end

app/controllers/naturesoft/projects/admin/images_controller.rb
module Naturesoft
  module Projects
    module Admin
      class ImagesController < Naturesoft::Admin::AdminController
        before_action :set_image, only: [:show, :edit, :update, :destroy, :enable, :disable]
        before_action :default_breadcrumb
        
        # add top breadcrumb
        def default_breadcrumb
          add_breadcrumb "Images Of Projects", naturesoft_projects.admin_images_path
        end
    
        # GET /images
        def index
          @images = Image.search(params).paginate(:page => params[:page], :per_page => 10)
        end
    
        # GET /images/1
        def show
          add_breadcrumb @image.name, naturesoft_projects.new_admin_image_path
          add_breadcrumb "Show"
        end
    
        # GET /images/new
        def new
          @image = Image.new
          add_breadcrumb "New Image", naturesoft_projects.new_admin_image_path
        end
    
        # GET /images/1/edit
        def edit
          add_breadcrumb @image.name, naturesoft_projects.new_admin_image_path
          add_breadcrumb "Edit"
        end
    
        # POST /images
        def create
          @image = Image.new(image_params)
    
          if @image.save
            redirect_to admin_images_path, notice: 'Image was successfully created.'
          else
            render :new
          end
        end
    
        # PATCH/PUT /images/1
        def update
          if @image.update(image_params)
            redirect_to admin_images_path, notice: 'Image was successfully updated.'
          else
            render :edit
          end
        end
    
        # DELETE /images/1
        def destroy
          @image.destroy
          render text: 'Image was successfully destroyed.'
        end
        
        # ENABLE /images/stutus
        def enable
          @image.enable
          render text: "Status was sucessfully enabled"
        end
        
        # DISABLE /images/stutus
        def disable
          @image.disable
          render text: "Status was sucessfully disabled"
        end
        
        # DELETE /images/delete?ids=1,2,3
        def delete
          @images = Image.where(id: params[:ids].split(","))
          @images.destroy_all
          render text: 'Image (s) was successfully destroyed.'
        end
    
        private
          # Use callbacks to share common setup or constraints between actions.
          def set_image
            @image = Image.find(params[:id])
          end
    
          # Only allow a trusted parameter "white list" through.
          def image_params
            params.fetch(:image, {}).permit(:name, :discription, :image, :project_id)
          end
      end
    end
  end
end

app/controllers/naturesoft/projects/admin/option_controller.rb
module Naturesoft
  module Projects
    module Admin
      class OptionsController < Naturesoft::Admin::AdminController
        before_action :default_breadcrumb
        
        # add top breadcrumb
        def default_breadcrumb
          add_breadcrumb "Projects", naturesoft_projects.admin_projects_path
        end
    
        # GET /partners
        def index
          add_breadcrumb "Settings", nil
          
          @options = Naturesoft::Option.options("projects")
        end
      end
    end
  end
end

app/controllers/naturesoft/projects/admin/projects_controller.rb
module Naturesoft
  module Projects
    module Admin
      class ProjectsController < Naturesoft::Admin::AdminController
        before_action :set_project, only: [:show, :edit, :update, :destroy, :enable, :disable]
        before_action :default_breadcrumb
        
        # add top breadcrumb
        def default_breadcrumb
          add_breadcrumb "Projects", naturesoft_projects.admin_projects_path
        end
    
        # GET /projects
        def index
          @projects = Project.search(params).paginate(:page => params[:page], :per_page => Naturesoft::Option.get("projects", "items_per_page"))
        end
    
        # GET /projects/1
        def show
          add_breadcrumb @project.name, naturesoft_projects.new_admin_project_path
          add_breadcrumb "Show"
        end
    
        # GET /projects/new
        def new
          @project = Project.new
          add_breadcrumb "New Project", naturesoft_projects.new_admin_project_path
        end
    
        # GET /projects/1/edit
        def edit
          add_breadcrumb @project.name, naturesoft_projects.new_admin_project_path
          add_breadcrumb "Edit"
        end
    
        # POST /projects
        def create
          @project = Project.new(project_params)
          @project.categories.clear
          @project.user = current_user
          if params[:category_ids].present?
            params[:category_ids].each do |id|      
              @project.categories << Category.find(id)
            end
          end
    
          if @project.save
            redirect_to admin_projects_path, notice: 'Project was successfully created.'
          else
            render :new
          end
        end
    
        # PATCH/PUT /projects/1
        def update
          @project.categories.clear
          if params[:category_ids].present?
            params[:category_ids].each do |id|      
              @project.categories << Category.find(id)
            end
          end
          if @project.update(project_params)
            redirect_to admin_projects_path, notice: 'Project was successfully updated.'
          else
            render :edit
          end
        end
    
        # DELETE /projects/1
        def destroy
          @project.destroy
          render text: 'Project was successfully destroyed.'
        end
        
        # ENABLE /partners/stutus
        def enable
          @project.enable
          render text: "Status was sucessfully enabled"
        end
        
        # DISABLE /partners/stutus
        def disable
          @project.disable
          render text: "Status was sucessfully disabled"
        end
        
        # DELETE /projects/delete?ids=1,2,3
        def delete
          @projects = Project.where(id: params[:ids].split(","))
          @projects.destroy_all
          render text: 'Project(s) was successfully destroyed.'
        end
    
        private
          # Use callbacks to share common setup or constraints between actions.
          def set_project
            @project = Project.find(params[:id])
          end
    
          # Only allow a trusted parameter "white list" through.
          def project_params
            params.fetch(:project, {}).permit(:name,
              :description,
              :website,
              :investor,
              :start_date,
              :end_date,
              :category_id,
              images_attributes: [:id, :is_main, :image, :name, :_destroy]
            )
          end
      end
    end
  end
end

app/controllers/naturesoft/projects/backend/categories_controller.rb
module Naturesoft
  module Projects
    module Backend
      class CategoriesController < Naturesoft::Backend::BackendController
        before_action :set_category, only: [:show, :edit, :update, :destroy, :enable, :disable]
        before_action :default_breadcrumb
        
        # add top breadcrumb
        def default_breadcrumb
          add_breadcrumb "Categories Of Projects", naturesoft_projects.backend_categories_path
        end
    
        # GET /categories
        def index
          @categories = Category.search(params).paginate(:page => params[:page], :per_page => 10)
        end
    
        # GET /categories/1
        def show
          add_breadcrumb @category.name, naturesoft_projects.new_backend_category_path
          add_breadcrumb "Show"
        end
    
        # GET /categories/new
        def new
          @category = Category.new
          add_breadcrumb "New Category", naturesoft_projects.new_backend_category_path
        end
    
        # GET /categories/1/edit
        def edit
          add_breadcrumb @category.name, naturesoft_projects.new_backend_category_path
          add_breadcrumb "Edit"
        end
    
        # POST /categories
        def create
          @category = Category.new(category_params)
          @category.user = current_user
    
          if @category.save
            redirect_to backend_categories_path, notice: 'Category was successfully created.'
          else
            render :new
          end
        end
    
        # PATCH/PUT /categories/1
        def update
          if @category.update(category_params)
            redirect_to backend_categories_path, notice: 'Category was successfully updated.'
          else
            render :edit
          end
        end
    
        # DELETE /categories/1
        def destroy
          @category.destroy
          render text: 'Category was successfully destroyed.'
        end
        
        # ENABLE /categories/stutus
        def enable
          @category.enable
          render text: "Status was sucessfully enabled"
        end
        
        # DISABLE /categories/stutus
        def disable
          @category.disable
          render text: "Status was sucessfully disabled"
        end
        
        # DELETE /categories/delete?ids=1,2,3
        def delete
          @categories = Category.where(id: params[:ids].split(","))
          @categories.destroy_all
          render text: 'Categor(y/ies) was successfully destroyed.'
        end
        
        # GET /articles/select2
        def select2
          render json: Category.select2(params)
        end
    
        private
          # Use callbacks to share common setup or constraints between actions.
          def set_category
            @category = Category.find(params[:id])
          end
    
          # Only allow a trusted parameter "white list" through.
          def category_params
            params.fetch(:category, {}).permit(:name, :description)
          end
      end
    end
  end
end

app/controllers/naturesoft/projects/projects_controller.rb
module Naturesoft
  module Projects
    class ProjectsController < Naturesoft::FrontendController
      def list
        @projects = Naturesoft::Projects::Project.order(custom_order: "asc")
      end
      def projects_detail
        @project = Naturesoft::Projects::Project.find(params[:project_id])
      end
    end
  end
end

app/helpers/naturesoft/projects/application_helper.rb
module Naturesoft
  module Projects
    module ApplicationHelper
    end
  end
end

app/views/naturesoft/projects/backend/projects/_form.html.erb
<% if project.errors.any? %>
  <div class="alert alert-warning alert-bordered">
    <button type="button" class="close" data-dismiss="alert"><span>×</span><span class="sr-only">Close</span></button>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this slide from being saved:</h2>
  
      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

<div class="panel panel-flat">
  
  <div class="panel-heading"></div>
  
  <div class="panel-body">
    <%= form_for([naturesoft_projects, :backend, project], html: {class: "form-horizontal validate", multipart: true}) do |f| %>
    
      <div class="tabbable">
        <ul class="nav nav-tabs nav-tabs-bottom">
          <li class="active"><a href="#right-icon-tab1" data-toggle="tab" aria-expanded="true"><i class=" icon-spinner4 position-left"></i> Genaral</a></li>
          <li class=""><a href="#right-icon-tab2" data-toggle="tab" aria-expanded="false"><i class="icon-attachment position-left"></i> Pictures</a></li>
        </ul>
  
        <div class="tab-content">
          <div class="tab-pane active" id="right-icon-tab1">
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label class="col-md-12 control-label" ><%= t(:name) %> <span class='text-danger'>*</span></label>
                  <div class="col-md-12">
                    <%= f.text_field :name, class: "form-control required" %>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label class="col-md-12 control-label" ><%= t(:investor) %> <span class='text-danger'>*</span></label>
                  <div class="col-md-12">
                    <%= f.text_field :investor, class: "form-control required" %>
                  </div>
                </div>
              </div>
            </div>
            
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label class="col-md-12 control-label" ><%= t(:website) %> </label>
                  <div class="col-md-12">
                    <%= f.text_field :website, class: "form-control" %>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                <label class="col-md-12 control-label" ><%= t(:category) %> <span class='text-danger'>*</span></label>
                <div class="col-md-12">
                  <div class="input-group">
                    
                      <% selected = options_for_select((project.categories.map {|c| [c.name, c.id]}),project.categories.map(&:id)) %>
                      <%= select_tag("category_ids[]",
                        selected,
                        {
                          class: "select2-ajax required",
                          include_blank: "none",
                          multiple: "multiple",
                          "data-url": select2_backend_categories_path,
                        }
                      ) %>
                      <span class="input-group-btn">
                        <a class="btn btn-info" href="<%= naturesoft_projects.new_backend_category_path %>"><i class="icon-plus2"></i></a>
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
              
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label class="col-md-12 control-label" ><%= t(:start_date) %> </label>
                  <div class="col-md-12">
                    <%= f.text_field :start_date, class: "form-control" %>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label class="col-md-12 control-label" ><%= t(:end_date) %> </label>
                  <div class="col-md-12">
                    <%= f.text_field :end_date, class: "form-control" %>
                  </div>
                </div>
              </div>
            </div>
            
            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label class="col-md-12 control-label" ><%= t(:description) %> </label>
                  <div class="col-md-12">
                    <%= f.text_area :description, class: "form-control", style: "min-width:100%;max-width:100%" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
  
          <div class="tab-pane addable-form" data-sample="image-form" id="right-icon-tab2">
            <div class="addable-container">
              <% project.images.each_with_index do |image,index| %>
                <%= render "image_form", item: image, index: index %>
              <% end %>
            </div>
            <div class="row">
              <div class="col-md-2">
                <div class="text-left">
                  <a href="#add" class="btn btn-info addable-add">Add Image <i class="icon-plus2 position-center"></i></a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="text-right">
        <%= button_tag "#{t(:save)}<i class=\"icon-check position-right\"></i>".html_safe, class: "btn btn-primary"%>
      </div>
      
    <% end %>
  </div>
</div>

<!-- thumbnail size sample form -->
<div class="image-form hide">
  <%= render 'image_form', item: Naturesoft::Projects::Image.new, index: "<<index>>" %>
</div>
<!--/thumbnail size sample form -->

app/views/naturesoft/projects/backend/projects/_image_form.html.erb
            <%= hidden_field_tag "project[images_attributes]["+index.to_s+"][id]", item.id %>
            <%= hidden_field_tag "project[images_attributes]["+index.to_s+"][user_id]", current_user.id %>
            <div class="row addable-row" data-index="<%= index %>">
              <div class="col-md-5">
                <div class="form-group">
                  <label class="col-md-3 control-label" ><%= t(:image) %> <span class='text-danger'>*</span></label>
                  <div class="media no-margin-top col-md-9">
                    <div class="media-left">
                      <a href="#">
                          <img src="<%= image_src(item.image.system) %>" style="width: 50px; height: auto; border-radius: 2px;" alt="">
                      </a>
                    </div>
              
                    <div class="media-body">
                      <input type="file" name="project[images_attributes][<%= index %>][image]" class="">
                      <span class="help-block">Accepted formats: gif, png, jpg.</span>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="form-group">
                  <label class="col-md-2 control-label" ><%= t(:name) %> </label>
                  <div class="col-md-10">
                    <input value="<%= item.name %>" class="form-control" name="project[images_attributes][<%= index %>][name]" />
                  </div>
                </div>
              </div>
              <div class="col-md-1 hide">
                <div class="form-group">
                  <div><%= t(:remove) %> </div>
                  <div class="">
                    <input type="checkbox" value="true" class="checkbox delete" name="project[images_attributes][<%= index %>][_destroy]" />
                  </div>
                </div>
              </div>
              <div class="col-md-1">
                <div class="form-group">                  
                  <div class="">
                    <input type="hidden" value="false" name="project[images_attributes][<%= index %>][is_main]" />
                    <input check-group="project_image_main" type="radio" <%= "checked=checked" if item.is_main %> value="true" class="checkbox" name="project[images_attributes][<%= index %>][is_main]" />
                  </div>
                  <div><%= t(:default) %></div>
                </div>
              </div>
              <div class="col-md-1">
                <a href="#add" class="btn btn-danger addable-nested-remove"><i class="icon-cross2"></i></a>
              </div>
              <hr style="clear: both" />
            </div>
            

app/views/naturesoft/projects/backend/projects/edit.html.erb
<% title "Edit Project" %>

<%= render 'form', project: @project %>

app/views/naturesoft/projects/backend/projects/new.html.erb
<% title "New Project" %>

<%= render 'form', project: @project %>

app/views/naturesoft/projects/backend/projects/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>